env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "airbnb"

parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - "project" # To assign project ID
        - "item" # To assign todo ID
